---

name: Ansible Lint

on:
  #  Friday at 02:17 UTC (~3:17 AM CET / 4:17 AM CEST). Actual start time depends on GitHub load.
  schedule:
    - cron: '17 2 * * 5'

  # Validate open pull requests
  pull_request:
    branches:
      - stage
      - dev

  # Runs on push to dev and main branches
  push:
    branches:
      - dev
      - main

  # Enable manual start button
  workflow_dispatch:

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      # The shared file is available only in 'dev' and 'stage' branches,
      # as it is removed during publishing workflow into 'main' branch.
      # Scenario 'sap_hana' is used as source for 'main' branch.
      - name: Determine requirements file path
        id: get_path
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "REQUIREMENTS_PATH=./deploy_scenarios/sap_hana/ansible_requirements.yml" >> $GITHUB_ENV
          else
            echo "REQUIREMENTS_PATH=./common_fragments/ansible_requirements.yml" >> $GITHUB_ENV
          fi

        # Use @vXX to automatically track the latest release from the year 20XX. Example: @v26 for 2026.
        # ansible-lint uses Calendar Versioning (e.g., v26.0.0 -> YYYY.MM.PATCH).
        # Avoid using @main, which can introduce breaking changes unexpectedly.
      - uses: ansible/ansible-lint@v26
        with:
          requirements_file: ${{ env.REQUIREMENTS_PATH }}
